#!/bin/bash

function create_user() {
	useradd -M $uname
	echo "$uname:$pass" | chpasswd
	usermod -e $expdate $uname
	myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`;
	myip2="s/xxxxxxxxx/$myip/g";
	echo " ";
	echo " ";
	echo " ";
	echo " ";
	echo "System by MuLuu09

For support:-
Email: muluu09@gmail.com
My Facebook: https://www.facebook.com/mohdfazren
SMS/Telegram/Whatsapp: +601131731782

";
	echo "Details for you account";
	echo " ";
	echo "Username : $uname";
	echo "Password : $pass";
	echo "Expired Date : $expdate";
	echo " ";
	echo "[ TQ buy account from MappakkoE VPN/SSH ]";
	echo " ";
	echo " ";
	echo " ";
	echo " ";
}

function renew_user() {
	echo " ";
	echo " ";
	echo " ";
	echo " ";
	echo " ";
	echo "System by MuLuu09

For support:-
Email: muluu09@gmail.com
My Facebook: https://www.facebook.com/mohdfazren
SMS/Telegram/Whatsapp: +601131731782

";
	echo "Details for you account renew";
	echo " ";
	echo "Username : $uname";
	echo "New Expired Date : $expdate";
	echo " ";
	echo "[ TQ renew you account from MappakkoE VPN/SSH ]";
	usermod -e $expdate $uname
	echo " ";
	echo " ";
	echo " ";
	echo " ";
	echo " ";
}

function delete_user(){
	userdel $uname
	echo "Done delete $uname";
}

function expired_users(){
	cat /etc/shadow | cut -d: -f1,8 | sed /:$/d > /tmp/expirelist.txt
	totalaccounts=`cat /tmp/expirelist.txt | wc -l`
	for((i=1; i<=$totalaccounts; i++ )); do
		tuserval=`head -n $i /tmp/expirelist.txt | tail -n 1`
		username=`echo $tuserval | cut -f1 -d:`
		userexp=`echo $tuserval | cut -f2 -d:`
		userexpireinseconds=$(( $userexp * 86400 ))
		todaystime=`date +%s`
		if [ $userexpireinseconds -lt $todaystime ] ; then
			echo $username
		fi
	done
	rm /tmp/expirelist.txt
}

function not_expired_users(){
    cat /etc/shadow | cut -d: -f1,8 | sed /:$/d > /tmp/expirelist.txt
    totalaccounts=`cat /tmp/expirelist.txt | wc -l`
    for((i=1; i<=$totalaccounts; i++ )); do
        tuserval=`head -n $i /tmp/expirelist.txt | tail -n 1`
        username=`echo $tuserval | cut -f1 -d:`
        userexp=`echo $tuserval | cut -f2 -d:`
        userexpireinseconds=$(( $userexp * 86400 ))
        todaystime=`date +%s`
        if [ $userexpireinseconds -gt $todaystime ] ; then
            echo $username
        fi
    done
	rm /tmp/expirelist.txt
}

function used_data(){
	myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`
	myint=`ifconfig | grep -B1 "inet addr:$myip" | head -n1 | awk '{print $1}'`
	ifconfig $myint | grep "RX bytes" | sed -e 's/ *RX [a-z:0-9]*/Received: /g' | sed -e 's/TX [a-z:0-9]*/\nTransfered: /g'
}

clear
echo "System by MuLuu09

For support:-
Email: muluu09@gmail.com
My Facebook: https://www.facebook.com/mohdfazren
SMS/Telegram/Whatsapp: +601131731782

";
PS3='Please enter your choice: '
options=("Tambah User" "Renew User" "Padam User" "Connected Users" "User List" "Ram Status" "Users Tidak Expired" "Expired Users" "Used Data By Users" "Current Connected OpenVPN" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "Tambah User")
            read -p "Masukkan username: " uname
            read -p "Masukkan password: " pass
            read -p "Masukkan expiry date (YYYY-MM-DD): " expdate
	    create_user
	    break
            ;;
        "Renew User")
            read -p "Masukkan username untuk renew: " uname
            read -p "Masukkan expiry date (YYYY-MM-DD): " expdate
            renew_user
            break
            ;;
        "Padam User")
            read -p "Masukkan username untuk dipadam: " uname
            padam_user
            break
            ;;
		"Connected Users")
            monssh
            break
            ;;		
		"User List")
            user-list
            break
            ;;	
		"Ram Status")
		    free -h | grep -v + > /tmp/ramcache
            cat /tmp/ramcache | grep -v "Swap"
            break
            ;;	
		"Users Tidak Expired")
			not_expired_users
			break
			;;
		"Expired Users")
			expired_users
			break
			;;
		"Used Data By Users")
			used_data
			break
			;;
   "Current Connected OpenVPN")
     status
     break
     ;;
        "Quit")
            break
            ;;
        *) echo invalid option;;
    esac
done
 
